"""Fix TaskStatus enum

Revision ID: 5b4b2a3e9d34
Revises: 
Create Date: 2025-12-14 12:34:05.754145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b4b2a3e9d34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.Enum('pending', 'completed', name='taskstatus'), nullable=False))
    op.add_column('tasks', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['name'], unique=True)
    op.drop_column('tasks', 'is_deleted')
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###
